docs(components): [tree] fix import error type
element-plus/element-plus pull request #10633
Opened 2022-11-17 03:44 UTC by init-qy

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

close #10619

2022-11-17 04:23 UTC, emojiiii requested changes

2022-11-17 04:23 UTC, emojiiii commented on docs/examples/tree/draggable.vue
> +import type { AllowDropType } from 'element-plus/es/components/tree/src/tree.type'
应该是 `NodeDropType` 类型才对

2022-11-17 05:04 UTC, init-qy commented on docs/examples/tree/draggable.vue
> +import type { AllowDropType } from 'element-plus/es/components/tree/src/tree.type'
dropType的改动发生在 #8681
另外在文档中对于type的描述也多次出现 `node drop type (before / after / inner)`
所以这边demo中使用 `AllowDropType` 是没有问题的

2022-11-17 06:57 UTC, emojiiii commented on docs/examples/tree/draggable.vue
> +import type { AllowDropType } from 'element-plus/es/components/tree/src/tree.type'
> dropType的改动发生在 #8681 的确应该是`NodeDropType` 另外在文档中对于type的描述多次出现 `node drop type (before / after / inner)` 和`export declare type NodeDropType = 'before' | 'after' | 'inner' | 'none'` 仍有出入 是否需要修改

暂时不更改，这个组件的类型有点乱，需要统一再重新整理一遍

2022-11-17 06:58 UTC, emojiiii approved these changes

2022-11-17 09:38 UTC, chenxch approved these changes

2022-11-20 08:22 UTC, holazz approved these changes

2022-11-20 08:22 UTC, merged