fix(components): [tree-select] disabled attribute does not take effect
element-plus/element-plus pull request #10670
Opened 2022-11-19 06:36 UTC by iDestin

Add default values for attributes, fix #10648

closed #10648

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

2022-11-22 09:31 UTC, iDestin commented
can anyone help me review this? 🤓

2022-12-03 13:04 UTC, tolking approved these changes

2023-01-02 11:46 UTC, iDestin commented
@yujinpan can you help me review this?

2023-01-03 03:14 UTC, yujinpan requested changes

2023-01-03 03:14 UTC, yujinpan commented on packages/components/virtual-list/__tests__/dynamic-size-list.test.ts
> +      ).toBeLessThanOrEqual(BASE_SIZE + 5 * 12)
Should not modify other unrelated code, no matter what the problem.

2023-01-10 13:59 UTC, iDestin commented
@yujinpan done PTAL

2023-01-13 08:38 UTC, yujinpan approved these changes
LGTM

2023-01-14 23:50 UTC, merged