Feat/empty
element-plus/element-plus pull request #1210
Opened 2021-01-06 11:12 UTC by kooriookami

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

2021-01-07 03:12 UTC, JeremyWuuuuu commented on packages/empty/package.json
> +    "vue": "^3.0.3"
Change to `^3.0.5`

2021-01-07 03:13 UTC, JeremyWuuuuu commented on packages/empty/src/img-empty.vue
> +    height="86px"
I think these 2 attributes can be removed. Could you remove it and see if it works?

2021-01-07 03:14 UTC, JeremyWuuuuu commented on packages/empty/src/img-empty.vue
> +      <g id="B-类空状态通用插图" transform="translate(-1268.000000, -535.000000)">
Replace this to English characters.

2021-01-07 03:15 UTC, JeremyWuuuuu commented on packages/empty/src/index.vue
> +      <img-empty v-else />
Change it this:

```suggestion
<slot name="image">
  <img-empty />
</slot>
```

2021-01-07 03:18 UTC, JeremyWuuuuu requested changes
Commented above which you need to address.

2021-01-07 04:36 UTC, JeremyWuuuuu commented on packages/empty/src/index.vue
>        <img v-if="image" :src="image" ondragstart="return false">
`@dragstart`?

2021-01-07 05:52 UTC, JeremyWuuuuu approved these changes

2021-01-07 05:52 UTC, merged

2021-01-16 23:48 UTC, jikoy commented
Where is the demo ?

2021-01-17 03:09 UTC, zazzaz commented
@jikoy https://element-plus.org/#/en-US/component/empty