Feat/radio
element-plus/element-plus pull request #122
Opened 2020-08-07 16:33 UTC by zazzaz

- [x] Component Migration

Fix #98

2020-08-08 09:58 UTC, HerringtonDarkholme requested changes

2020-08-10 16:33 UTC, jw-foss requested changes

2020-08-11 06:49 UTC, merged

2020-10-30 03:00 UTC, Lliuxs commented on packages/radio/src/radio.vue
> +      <template v-if="!$slots.default">{{ label }}</template>
why not change radio-button to

2020-10-30 03:16 UTC, Lliuxs commented on packages/radio/src/radio.vue
> +    const elFormItem = inject('elFormItem')
const isDisabled = computed(() => {
      return isGroup.value
        ? radioGroup_.disabled || props.disabled || (elForm || {}).disabled
        : props.disabled || (elForm || {}).disabled
    })

{}.disabled 这样不好吧？