feat(loading): Add request data for empty logic display and reuse
element-plus/element-plus pull request #1448
Opened 2021-02-08 04:17 UTC by 1063428973

#

https://user-images.githubusercontent.com/32738523/107175359-914d2700-6a07-11eb-9ce2-bc68512af3ef.mp4

2021-02-08 19:49 UTC, nurlansu requested changes

2021-02-08 19:49 UTC, nurlansu commented on packages/loading/src/createLoadingComponent.ts
> +import Empty from '../../empty/src/index.vue'
Can't we use global import here?

```suggestion
import Empty from '@element-plus/empty'
```

2021-02-08 19:49 UTC, nurlansu commented on packages/loading/src/createLoadingComponent.ts
> +        !this.spinner ? spinner : noSpinner,
Can you change the order for better reading?

```suggestion
        this.spinner ? noSpinner : spinner,
```

2021-02-26 12:31 UTC, Ryan2128 commented
Sorry, I think this pr should not be merged, beacuse we should only provide atomic component.

Your requirements can be obtained by combining loading and emptying, instead of adding new functions to atomic components.

What's your advice? @JeremyWuuuuu

2021-06-19 08:08 UTC, kooriookami commented
Thanks for your PR, but this might not a good change. So I close it.

2021-06-19 08:08 UTC, closed without merging