fix(components): [input-number] Improve modelValue prop type
element-plus/element-plus pull request #16124
Opened 2024-03-13 03:13 UTC by XL-YiBai

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### Description
The acceptable types for value-on-clear prop are: 'min' | 'max' | null | number.

When clearing the input box, the value bound with the v-model may be modified to null | undefined | number. Therefore, modelValue should be allowed to accept null type.

### Related Issue
[#14848 ](https://github.com/element-plus/element-plus/issues/14848)

2024-05-03 02:08 UTC, btea commented
Can you handle the code conflict?

2024-05-08 09:58 UTC, XL-YiBai commented
Hi @btea , I have resolved the code conflict. Could you please review the PR again? Thanks.🍺

2024-05-08 10:18 UTC, FrontEndDog approved these changes

2024-05-08 10:18 UTC, FrontEndDog commented
Thanks!

2024-05-08 11:19 UTC, btea approved these changes

2024-05-09 01:57 UTC, kooriookami commented
All other props should accept `null` or `undefined`. Refer to doc of Vue. What do you think?

https://vuejs.org/guide/components/props.html#prop-validation

```
(`null` and `undefined` values will allow any type)
```

2024-05-09 03:34 UTC, XL-YiBai commented
If prop fail Vue's verification, a warning will be thrown on the console: `[Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected Number with value 1, got String with value "1".`.
`null` and `undefined` can indeed pass Vue's validation, but in fact, if only the `modelValue` type is specified as `Number`, then when `n` is of type `number | null`, using `v-model="n"` will give the following prompt in VScode:
<img width="893" alt="image" src="https://github.com/element-plus/element-plus/assets/119273236/ff6c57b6-440f-4eea-9cc7-31e0cd8d1148">

2025-05-20 09:19 UTC, kooriookami requested changes

2025-05-20 09:19 UTC, kooriookami commented on packages/components/input-number/src/input-number.ts
> +    validator: (val: number | null) => val === null || isNumber(val),
```suggestion
```

2025-05-20 09:19 UTC, kooriookami commented on packages/components/input-number/src/input-number.ts
> +    validator: (val: number | null) => val === null || isNumber(val),
No need to add a validator.

2025-05-20 09:23 UTC, kooriookami commented
Please resolve the conflicts, then this PR can be merged.

2025-05-20 09:24 UTC, kooriookami approved these changes

2025-05-20 09:25 UTC, XL-YiBai commented
Thanks 🍻

2025-05-20 09:29 UTC, merged

2025-05-22 09:20 UTC, JCL206312 commented
However, ColorPicker also has the same problem, after clicking the clear, the value of v-model will also become null