fix(table): the current row render flashing when expanding line toggle
element-plus/element-plus pull request #1654
Opened 2021-03-17 07:31 UTC by justwiner

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

2021-03-22 01:13 UTC, Ryan2128 requested changes

2021-03-22 01:13 UTC, Ryan2128 commented on packages/table/src/table-body/render-helper.ts
> +      // TIP: 暂时使用一维数组，避免渲染闪烁，$index被修改的情况，经测试暂未发现
Maybe English annotations are better?

2021-03-24 02:03 UTC, justwiner commented on packages/table/src/table-body/render-helper.ts
> +      // TIP: 暂时使用一维数组，避免渲染闪烁，$index被修改的情况，经测试暂未发现
done

2021-03-25 07:46 UTC, Ryan2128 approved these changes

2021-03-27 11:12 UTC, JeremyWuuuuu approved these changes

2021-03-27 11:12 UTC, merged