fix(table): #1653
element-plus/element-plus pull request #1665
Opened 2021-03-19 03:06 UTC by justwiner

Fix table can not correctly calculate bug of cell width after sorting or filtering

fix #1653

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

2021-03-22 01:12 UTC, Ryan2128 requested changes

2021-03-22 01:12 UTC, Ryan2128 commented on packages/table/src/table-layout.ts
> +      // bodyHeight无值时，表示未设置table高度，永远不会出现滚动条
Maybe English annotations are better?

2021-03-24 01:59 UTC, justwiner commented on packages/table/src/table-layout.ts
> +      // bodyHeight无值时，表示未设置table高度，永远不会出现滚动条
Done

2021-03-25 07:42 UTC, JeremyWuuuuu approved these changes

2021-03-25 07:46 UTC, Ryan2128 approved these changes

2021-03-26 07:13 UTC, merged