Feat/pagination
element-plus/element-plus pull request #195
Opened 2020-08-25 03:41 UTC by PannanaAlex

- [x] Component Migration

Fix #120

2020-08-28 07:45 UTC, SimonaliaChen commented on packages/pagination/src/next.ts
> +  template: `
why not use `.vue` and `<template>`

2020-08-28 07:45 UTC, SimonaliaChen commented on packages/pagination/src/jumper.ts
> +      前往 <input @keyup='handleKeyup'/> 页
Deal with i18n

2020-09-10 08:32 UTC, bastarder commented on packages/pagination/src/index.ts
> +      slot: h('span', {}, this.$slots.default ? this.$slots.default() : ''),
this.$slots.default?.()
in `element-ui`, no span wrapper

2020-09-10 08:32 UTC, bastarder commented on packages/pagination/src/index.ts
> +    const components = layout.split(',').map((item: any) => item.trim())
```suggestion
    const components = layout.split(',').map((item: string) => item.trim())
```

2020-09-10 08:34 UTC, zouhangwithsweet commented on packages/pagination/src/jumper.vue
> +      @input="handleInput"
yep, good suggesion

2020-09-28 19:51 UTC, g3r4n requested changes

2020-09-28 19:51 UTC, g3r4n commented on packages/pagination/src/sizes.ts
> +  methods: {
watch and methods into the setup ?

2020-10-09 04:04 UTC, HerringtonDarkholme approved these changes

2020-10-09 04:04 UTC, merged

2020-11-18 12:05 UTC, Lliuxs commented
不传layout的 在查看dom结构的时候发现有一个el-pagination__rightwrapper结构 不知所云 
默认值中的  -> 就是简单的想让后面的不渲染吗？  rightWrapperChildren 设计的意义在哪 是否能解答下