feat(components): [el-message] & [el-notification] appendTo option added
element-plus/element-plus pull request #4012
Opened 2021-10-23 10:44 UTC by codespikex

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

#4011

2021-10-25 01:36 UTC, sxzz approved these changes

2021-10-25 01:38 UTC, sxzz requested changes
Fix unit test please

2021-10-27 20:53 UTC, sxzz approved these changes

2021-10-30 14:08 UTC, JeremyWuuuuu approved these changes

2021-10-30 14:09 UTC, merged