refactor(components): refactor progress
element-plus/element-plus pull request #4285
Opened 2021-11-08 03:57 UTC by Alanscut

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.
#3113

2021-11-08 18:37 UTC, sxzz commented on packages/components/progress/src/progress.ts
> +      ['', 'success', 'exception', 'warning'].indexOf(val) > -1,
please use `values` property

2021-11-08 18:47 UTC, sxzz requested changes
Also, please fix all typescript errors.

2021-11-08 18:47 UTC, sxzz commented on packages/components/progress/src/progress.ts
> +type ProgressFuncType = (percentage: number) => string
Suggestion: rename it to `ProgressFn`

2021-11-08 18:47 UTC, sxzz commented on packages/components/progress/src/progress.ts
> +    validator: (val: string): boolean =>
please use `values` property

2021-11-08 18:47 UTC, sxzz commented on packages/components/progress/src/progress.ts
> +})
add `as const`

2021-11-08 18:47 UTC, sxzz commented on packages/components/progress/src/progress.ts
> +    default: () => 'round' as NonNullable<SVGAttributes['stroke-linecap']>,
```suggestion
    default: 'round',
```

2021-11-08 18:47 UTC, sxzz commented on packages/components/progress/src/progress.ts
> +import type { ExtractPropTypes } from '@vue/runtime-core'
```suggestion
import type { ExtractPropTypes } from 'vue'
```

2021-11-09 01:54 UTC, Alanscut commented
@sxzz The problems you raised have been fixed, please check again

2021-12-09 19:10 UTC, sxzz approved these changes

2021-12-09 19:15 UTC, merged