feat(components): [el-input,el-inut-number] custom-namespace
element-plus/element-plus pull request #5440
Opened 2022-01-17 18:06 UTC by Valar103769

为 `el-input` 和 `el-input-numer` 组件添加命名空间支持

2022-01-17 22:35 UTC, sxzz commented on packages/hooks/use-namespace/index.ts
> +    el,
Why to add `el`?

2022-01-17 22:35 UTC, sxzz commented
可以参考 https://github.com/element-plus/element-plus/pull/5377/files 来修改

2022-01-18 02:08 UTC, Valar103769 commented on packages/hooks/use-namespace/index.ts
> +    el,
> 
1. 因为我想要直接可用的字符串, 但是 `useNamespace` 返回的 `nasespace`是个ref,
2. 并且我只想要一个 `el` 字符串的映射,但是 `useNamespace` 需要传入 `block` ,我觉得 `namespace` 不应该跟任何 `block` 有关联,
3. 其他的 `be` , `em` 之类的方法, 因为内部命名晦涩以及内部代码拼接太严格, 至少目前还没使用到这么复杂的拼接方式

因此添加el 变量, 直接获取 `namespace`,
而且叫 `el` , 代码更好读一些
以上是我的理解

2022-01-18 02:11 UTC, sxzz commented on packages/hooks/use-namespace/index.ts
> +    el,
/cc @iamkun

2022-01-18 03:07 UTC, msidolphin commented
请参考这个issue https://github.com/element-plus/element-plus/issues/5374 不要改动到已分配的

2022-01-18 03:13 UTC, msidolphin commented on packages/hooks/use-namespace/index.ts
> +    el,
> > 
> 
> 1. 因为我想要直接可用的字符串, 但是 `useNamespace` 返回的 `nasespace`是个 `ref`,
> 2. 其他的 `be` , `em` 之类的方法, 虽然可以获取字符串, 但是命名晦涩以及内部实现太严格,就没用他们,
> 
> 因此添加 `el` 变量, 直接获取`unref`的 `namespace`, 并且 `el` 原本就是 `useNamespace` 的中间变量,相当于一个原子, `el` 仅仅是把它抛出 而且叫 `el` , 代码更好读一些 以上是我的理解

el本身就是namespace啊，使用namespace是我们达成的共识，而且这么改了之后这些值都不会是reactive的

2022-01-18 05:13 UTC, Valar103769 commented on packages/hooks/use-namespace/index.ts
> +    el,
修改了,你们再看一下,是这样的吗? @sxzz @msidolphin

2022-01-18 05:23 UTC, Valar103769 commented
> 请参考这个issue #5374 不要改动到已分配的

你们都分配完了啊🤔

2022-01-18 07:26 UTC, msidolphin commented
> > 请参考这个issue #5374 不要改动到已分配的
> 
> 你们都分配完了啊🤔

还没啊，你想改的话在组件后面@自己

2022-01-18 07:27 UTC, msidolphin commented on packages/components/input-number/src/input-number.vue
> +      `${namespace}-input-number`,
Please refer to the the button, eg: `ns.b('input-number')`

2022-01-18 11:06 UTC, sxzz commented
你可以参考下我的PR来修改

https://github.com/element-plus/element-plus/pull/5461
https://github.com/element-plus/element-plus/pull/5462
https://github.com/element-plus/element-plus/pull/5456
https://github.com/element-plus/element-plus/pull/5454
https://github.com/element-plus/element-plus/pull/5468

2022-01-18 11:08 UTC, sxzz commented on packages/components/input/src/input.vue
> +    const { namespace } = useNamespace()
```suggestion
    const ns = useNamespace('input')
```

2022-01-18 11:08 UTC, sxzz commented on packages/components/input/src/input.vue
> +        el.querySelectorAll(`.${namespace.value}-input__${place}`)
```suggestion
        el.querySelectorAll(`.${ns.e(place)}`)
```

2022-01-18 11:08 UTC, sxzz commented on packages/components/input/src/input.vue
> +          el.querySelector(`.${namespace.value}-input-group__${pendant}`)
```suggestion
          el.querySelector(`.${ns.be('group', pendant)`)
```

2022-01-18 11:08 UTC, sxzz commented on packages/components/input/src/input.vue
> +      namespace,
```suggestion
      ns,
```

2022-01-18 11:08 UTC, sxzz commented on packages/hooks/use-namespace/index.ts
> +export const useNamespace = (block = '') => {
Revert this change.

2022-01-18 14:14 UTC, sxzz requested changes

2022-01-18 14:14 UTC, sxzz commented on packages/components/input-number/src/input-number.vue
> +      :class="[ns.e('decrease'), { 'is-disabled': minDisabled }]"
```suggestion
      :class="[ns.e('decrease'), ns.is('disabled', minDisabled)]"
```

2022-01-18 14:14 UTC, sxzz commented on packages/components/input-number/src/input-number.vue
> +      :class="[ns.e('increase'), { 'is-disabled': maxDisabled }]"
Same here

2022-01-18 14:14 UTC, sxzz commented on packages/components/input/src/input.vue
> +    const ns2 = useNamespace('textarea')
Rename it as `nsTextarea`

2022-01-18 14:14 UTC, sxzz commented on packages/components/input/src/input.vue
> +    const ns = useNamespace('input')
Rename it as `nsInput`

2022-01-18 14:14 UTC, sxzz commented on packages/components/input/src/input.vue
>          'is-exceed': inputExceed,
```suggestion
        [ns.is('disabled')]: inputDisabled,
        [ns.is('exceed')]': inputExceed,
```

2022-01-18 14:16 UTC, sxzz commented on packages/components/input-number/src/input-number.vue
>        { 'is-controls-right': controlsAtRight },
Same here

2022-01-18 14:49 UTC, sxzz commented on packages/components/input/src/input.vue
> +        [nsInput.is('disabled')]: inputDisabled,
```suggestion
       nsInput.is('disabled', inputDisabled)
```

2022-01-18 14:56 UTC, sxzz commented on packages/components/input/src/input.vue
> +        [nsInput.b('group--append')]: $slots.append,
Maybe we can add a new namespace `input-group` and use
```suggestion
        [nsInputGroup.m('append')]: $slots.append,
```

2022-01-18 15:06 UTC, sxzz commented on packages/components/input/src/input.vue
> +        [nsInput.b('group--append')]: $slots.append,
Wait. We can add a function called `bm`. And then we needn't add a new namespace.

2022-01-18 15:07 UTC, sxzz commented on packages/components/input/src/input.vue
> +        [nsInput.b('group--append')]: $slots.append,
I will add it in a new PR.

2022-01-19 04:39 UTC, closed without merging