refactor: refactor carousel to support namespace
element-plus/element-plus pull request #5553
Opened 2022-01-22 04:37 UTC by iamkun

Please make sure these boxes are checked before submitting your PR, thank you!
ref #5374
- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

2022-01-22 09:40 UTC, sxzz commented on packages/components/carousel/src/item.vue
> +      },
ns.is('active', data.active)

2022-01-22 09:40 UTC, sxzz commented on packages/components/carousel/src/item.vue
> +      type === 'card' ? ns.em('item', 'card') : '',
{[ns.em('item', 'card')]: type === 'card'}

2022-01-23 06:14 UTC, iamkun commented
fixed

2022-01-23 09:57 UTC, sxzz requested changes

2022-01-23 09:57 UTC, sxzz commented on packages/components/carousel/src/item.vue
> +      :class="ns.b('mask')"
```suggestion
      :class="ns.e('mask')"
```

2022-01-24 16:08 UTC, iamkun commented on packages/components/carousel/src/item.vue
> +      :class="ns.b('mask')"
my bad, fixed

2022-01-24 16:09 UTC, sxzz approved these changes

2022-01-24 16:12 UTC, sxzz approved these changes

2022-01-24 16:53 UTC, merged