refactor(components): [progress] use useNamespace
element-plus/element-plus pull request #5729
Opened 2022-01-30 15:42 UTC by buqiyuan

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

2022-02-07 21:39 UTC, sxzz commented on packages/components/progress/src/progress.vue
>      class="el-progress"
```suggestion
```
remove this

2022-02-07 21:41 UTC, sxzz requested changes
Please resolve the comment I left.

2022-02-08 02:16 UTC, buqiyuan commented
> Please resolve the comment I left.

ok, solved

2022-02-08 03:38 UTC, sxzz approved these changes

2022-02-08 03:38 UTC, merged