fix(components): [el-upload] jitter when remove file in the list
element-plus/element-plus pull request #6505
Opened 2022-03-09 09:01 UTC by msidolphin

before

https://user-images.githubusercontent.com/26672484/157407053-709d9fa6-7b1b-420a-bdc7-b90fc9c9adca.mp4

after

https://user-images.githubusercontent.com/26672484/157408000-d8cb1307-5f1f-4934-a84c-5e71ea6bce63.mp4

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

2022-03-10 07:25 UTC, JeremyWuuuuu commented
#6508 is refactoring this component, can we wait for it to see if we will still have this issue?

2022-03-10 07:46 UTC, sxzz commented
@JeremyWuuuuu There still seems to be this problem.

2022-03-10 15:52 UTC, sxzz commented
@msidolphin Could you please resolve conflicts?

2022-03-10 16:31 UTC, YunYouJun requested changes

2022-03-11 06:36 UTC, msidolphin commented on packages/theme-chalk/src/upload.scss
>      .#{$namespace}-icon--close {
> It seems to cause error position of photo wall close button.

<img width="979" alt="image" src="https://user-images.githubusercontent.com/26672484/157815271-1d70b6d5-ca2b-453d-827a-e183e522a78d.png">

fix～

2022-03-11 06:36 UTC, msidolphin commented
> @msidolphin Could you please resolve conflicts?

done

2022-03-11 06:51 UTC, JeremyWuuuuu approved these changes

2022-03-11 06:52 UTC, JeremyWuuuuu approved these changes

2022-03-11 07:31 UTC, YunYouJun approved these changes

2022-03-11 07:56 UTC, merged