refactor(components): [checkbox-button] switch to script-setup syntax
element-plus/element-plus pull request #7827
Opened 2022-05-21 10:12 UTC by chenxch

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

2022-05-21 10:12 UTC, chenxch commented
refactor plan #6114

2022-05-22 00:25 UTC, sxzz requested changes

2022-05-22 00:25 UTC, sxzz commented on packages/components/checkbox/src/checkbox-button.vue
> +  } as StyleValue
```suggestion
const activeStyle = computed<StyleValue>(() => {
  const fillValue = checkboxGroup?.fill?.value ?? ''
  return {
    backgroundColor: fillValue,
    borderColor: fillValue,
    color: checkboxGroup?.textColor?.value ?? '',
    boxShadow: fillValue ? `-1px 0 0 0 ${fillValue}` : null,
  }
```

2022-05-22 04:25 UTC, chenxch commented
@sxzz Thanks for your review, all processed.

2022-05-24 08:46 UTC, JeremyWuuuuu approved these changes

2022-05-24 08:51 UTC, sxzz approved these changes

2022-05-24 08:51 UTC, merged