feat(components): [autocomplete] autocomplete activate is error #8097
element-plus/element-plus pull request #8110
Opened 2022-06-05 16:49 UTC by zybieku

Please make sure these boxes are checked before submitting your PR, thank you!
fix #8097
- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

2022-06-06 06:16 UTC, zybieku commented
主要在点击选项的时候,做两件事 
1 控制列表的隐藏  调用close函数 : activated.value =false
2 取消input的焦点,故加上了blur 函数,方便下次点击在触发activated

2022-06-14 07:39 UTC, tolking commented
> 主要在点击选项的时候,做两件事 1 控制列表的隐藏 调用close函数 : activated.value =false 2 取消input的焦点,故加上了blur 函数,方便下次点击在触发activated

个人觉得失去焦点不是个好主意。如果只使用键盘操作，输入错误过后不是要 Tab 一圈回来修改？

2022-06-14 16:43 UTC, zybieku commented
> > 主要在点击选项的时候,做两件事 1 控制列表的隐藏 调用close函数 : activated.value =false 2 取消input的焦点,故加上了blur 函数,方便下次点击在触发activated
> 
> 个人觉得失去焦点不是个好主意。如果只使用键盘操作，输入错误过后不是要 Tab 一圈回来修改？

如果这种场景确实是!
失去焦点 只是为了下次再点击 能触发activated

2022-06-15 17:09 UTC, zybieku commented
> > 主要在点击选项的时候,做两件事 1 控制列表的隐藏 调用close函数 : activated.value =false 2 取消input的焦点,故加上了blur 函数,方便下次点击在触发activated
> 
> 个人觉得失去焦点不是个好主意。如果只使用键盘操作，输入错误过后不是要 Tab 一圈回来修改？

已经替换成不再失去焦点,通过listbox点击事件,拉起suggestionList

2022-06-16 01:34 UTC, chenxch commented
@zybieku 点击选项后，再次手动点击输入框，第一次出现的选项还是旧的哈。应该是focus被内部focus trap在modelValue赋值前触发了一次，联想用上一次的modelValue进行处理生成了选项哦。
然后我感觉还可以把blur暴露一下给外部，给使用者一个可以简单操作的地方。

2022-06-16 15:50 UTC, zybieku commented
> @zybieku 点击选项后，再次手动点击输入框，第一次出现的选项还是旧的哈。应该是focus被内部focus trap在modelValue赋值前触发了一次，联想用上一次的modelValue进行处理生成了选项哦。 然后我感觉还可以把blur暴露一下给外部，给使用者一个可以简单操作的地方。

已经解决
1.点击listbox时手动触发拉起getData刷新list数据
2 .expose blur function 供用户自己操作
3. 去掉focus的debounce延迟,否则拉起suggestionList 会先显示上一次的历史数据,再显示当前的list数据

2022-06-17 02:45 UTC, chenxch commented
@zybieku Good job! 👍

2022-06-17 06:41 UTC, tolking commented
@zybieku 测试未跑过，另外在选择后立即修改值是不会触发弹窗的

2022-06-17 10:20 UTC, zybieku commented
> @zybieku 测试未跑过
> 
> BUG: 在选择弹窗里面的值后立即修改值内容，没有触发弹窗
@tolking 
已经修改, select中的close()会和input冲突,现已经去掉
去掉了focus回调中的 debounce  ,同时 skip debounce 单测
**bug根本原因** :`下拉列表点击之后 ,会自动触发focus, 而且会回调多次`,虽在select事件之前触发,但是由于`debounce`延时加载,导致handleSelect中的清空逻辑无效
![image](https://user-images.githubusercontent.com/15903330/174279284-8f567976-a952-4f2f-8651-bd23a5590ed2.png)

对比了2.2.0 以前的版本,发现原来的版本 `下拉列表点击会自动blur,不会多次触发focus`

2022-06-17 14:08 UTC, tolking requested changes

2022-06-17 14:08 UTC, tolking commented on packages/components/autocomplete/__tests__/autocomplete.test.tsx
> +  test.skip('debounce / fetchSuggestions', async () => {
不应该直接跳过测试

虽然 focus 取消了抖动，但输入文字依然存在抖动。或许应该将测试内容改成模拟文字输入

// 单例

```diff
- await wrapper.find('input').trigger('focus')
- await wrapper.find('input').trigger('blur')
+ await wrapper.find('input').setValue('1')
```

2022-06-18 04:09 UTC, zybieku commented on packages/components/autocomplete/__tests__/autocomplete.test.tsx
> +  test.skip('debounce / fetchSuggestions', async () => {
已经修改

2022-06-18 04:40 UTC, tolking approved these changes

2022-06-18 04:47 UTC, tolking commented
似乎还存在问题：文档里面的 Remote search 无法选择，同时也是一直弹窗

2022-06-18 14:15 UTC, zybieku commented
> 似乎还存在问题：文档里面的 Remote search 无法选择，同时也是一直弹窗

@tolking sorry,开始没有考虑到Remote search 的场景,自测场景不到位,现在已经修改
> 问题原因是一样的,choose option 之后会多次触发focus, 从而触发远程延迟修改list的操作(比重置列表逻辑晚)
**修改内容**
1 移除focus触发刷新数据的逻辑,统一由listboxClick统一处理
2 移除input focus相关的单测,改成div listboxClick触发

2022-06-18 14:15 UTC, zybieku commented
> 似乎还存在问题：文档里面的 Remote search 无法选择，同时也是一直弹窗

@tolking sorry,开始没有考虑到Remote search 的场景,自测场景不到位,现在已经修改
> 问题原因是一样的,choose option 之后会多次触发focus, 从而触发远程延迟修改list的操作(比重置列表逻辑晚)
**修改内容**
1 移除focus触发刷新数据的逻辑,统一由listboxClick统一处理
2 移除input focus相关的单测,改成div listboxClick触发

2022-06-19 03:25 UTC, tolking commented
感谢你的贡献。但我觉得你的部分修改具有很大的破坏性质。我换了种方式修复这个问题

2022-06-19 03:46 UTC, zybieku commented
> 感谢你的贡献。但我觉得你的部分修改具有很大的破坏性质。我换了种方式修复这个问题

ok,只要能解决问题就行
其实也没多少破坏性,只是修掉本身 focus触发的不合理 
只是不想加太多的判断阻拦,那样并不是什么好代码,后面维护也很糟糕

2022-06-19 15:32 UTC, closed without merging