style(theme-chalk): dialog fix #9324
element-plus/element-plus pull request #9359
Opened 2022-08-18 07:46 UTC by lm312

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

2022-08-27 16:26 UTC, sxzz requested changes

2022-08-27 16:26 UTC, sxzz commented on packages/theme-chalk/src/dialog.scss
> +    max-height: calc(100vh - 200px);
Why `200px`?

2022-08-29 01:52 UTC, lm312 commented on packages/theme-chalk/src/dialog.scss
> +    max-height: calc(100vh - 200px);
el-dialog__header的高度+el-dialog__footer的高度+el-dialog__body的上下padding大致等于200px,所以el-dialog__body的maxHeight为calc(100vh - 200px)

2022-08-29 02:45 UTC, sxzz commented on packages/theme-chalk/src/dialog.scss
> +    max-height: calc(100vh - 200px);
不太清楚你要修复的是什么 bug 或优化的例子，可以先提供下，再讨论修复方案。硬编码 200px 是不太靠谱的。

2022-08-29 02:46 UTC, closed without merging